# Generated by Django 4.1.7 on 2023-03-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('city', models.CharField(default='Nairobi', max_length=50)),
                ('area', models.IntegerField(max_length=50)),
                ('estate', models.IntegerField(max_length=50)),
                ('house_number', models.IntegerField(max_length=50)),
                ('copies', models.IntegerField(max_length=50)),
                ('months', models.IntegerField(max_length=50)),
            ],
        ),
    ]
