# Generated by Django 4.1.7 on 2023-03-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoNewspaperSubscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='house_number',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='copies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='estate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='months',
            field=models.IntegerField(),
        ),
    ]
